#!/usr/bin/env node
/**
 * Sync app env files from root — only `.env` and `.env.local` per app.
 *
 * Edit:
 *   /.env         production / Docker (source of truth)
 *   /.env.local   local overrides (optional)
 *
 * Writes (never .env.development / .env.production):
 *   api/.env  api/.env.local
 *   admin/.env  admin/.env.local
 *   mobile/.env  mobile/.env.local
 *
 *   ./pinn env:sync
 *   ./pinn env:check
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const HDR =
  '# GENERATED by ./pinn env:sync from root .env — edit root, then re-run sync.\n' +
  '# Only .env and .env.local are used (no .env.development / .env.production).\n' +
  '# -----------------------------------------------------------------------------\n';

function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  for (const raw of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let val = line.slice(eq + 1);
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function dump(env, keys) {
  const lines = [];
  for (const key of keys) {
    if (env[key] === undefined || env[key] === '') continue;
    lines.push(`${key}=${env[key]}`);
  }
  return lines.join('\n') + (lines.length ? '\n' : '');
}

function write(rel, body) {
  const full = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, body, 'utf8');
  console.log(`  wrote ${rel}`);
}

function remove(rel) {
  const full = path.join(ROOT, rel);
  if (fs.existsSync(full)) {
    fs.unlinkSync(full);
    console.log(`  removed ${rel}`);
  }
}

/** Frontend-safe extras (never secrets like RAZORPAY_KEY_SECRET). */
const FRONTEND_EXTRA_KEYS = [
  'PORT',
  'HOSTNAME',
  'NODE_ENV',
  'API_BASE_URL',
  'API_VERSION',
  'API_TIMEOUT',
  'GOOGLE_MAPS_API_KEY',
  'RAZORPAY_KEY_ID',
];

function allKeys(env, prefixes = [], extra = FRONTEND_EXTRA_KEYS) {
  const keys = Object.keys(env).sort();
  if (!prefixes.length) return keys;
  return keys.filter(
    (k) => prefixes.some((p) => k.startsWith(p)) || extra.includes(k)
  );
}

function withDockerHosts(env) {
  const e = { ...env };
  const user = e.POSTGRES_USER || 'demo';
  const pass = e.POSTGRES_PASSWORD || 'demo';
  const db = e.POSTGRES_DB || 'pinpost';
  e.POSTGRES_HOST = 'db';
  e.REDIS_HOST = 'redis';
  e.DATABASE_URL = `postgresql://${user}:${pass}@db:5432/${db}`;
  const rp = e.REDIS_PASSWORD || '';
  e.REDIS_URL = rp
    ? `redis://:${rp}@redis:${e.REDIS_PORT || 6379}`
    : `redis://redis:${e.REDIS_PORT || 6379}`;
  if (e.API_PORT && !e.PORT) e.PORT = e.API_PORT;
  if (e.ADMIN_PORT && !e.PORT) e.PORT = e.ADMIN_PORT;
  return e;
}

function withLocalHosts(env) {
  const e = { ...env };
  const user = e.POSTGRES_USER || 'demo';
  const pass = e.POSTGRES_PASSWORD || 'demo';
  const db = e.POSTGRES_DB || 'pinpost';
  e.POSTGRES_HOST = 'localhost';
  e.REDIS_HOST = '127.0.0.1';
  e.DATABASE_URL = `postgresql://${user}:${pass}@localhost:5432/${db}`;
  const rp = e.REDIS_PASSWORD || '';
  e.REDIS_URL = rp
    ? `redis://:${rp}@127.0.0.1:${e.REDIS_PORT || 6379}`
    : `redis://127.0.0.1:${e.REDIS_PORT || 6379}`;
  // PORT is app-specific — set in sync() per target, not here.
  if (e.API_PORT && !e.PORT) e.PORT = e.API_PORT;
  e.NODE_ENV = e.NODE_ENV || 'development';
  e.DEV_MODE = e.DEV_MODE || 'true';
  return e;
}

// Keep in sync with api/src/config/environment.ts (plus POSTGRES_* for tooling).
const API_KEYS = [
  // Server
  'NODE_ENV',
  'PORT',
  'API_PORT',
  'API_VERSION',
  'API_BASE_URL',
  'DEV_MODE',
  'EXPIRED_NOTIFICATION_DEBUG',
  // Database
  'POSTGRES_DB',
  'POSTGRES_USER',
  'POSTGRES_PASSWORD',
  'POSTGRES_HOST',
  'DATABASE_URL',
  // Auth
  'JWT_SECRET',
  'JWT_EXPIRES_IN',
  'BCRYPT_ROUNDS',
  // Redis / jobs
  'REDIS_URL',
  'REDIS_HOST',
  'REDIS_PORT',
  'REDIS_PASSWORD',
  'REDIS_DB',
  'JOB_QUEUE_ENABLED',
  'JOB_CONCURRENCY',
  'JOB_MAX_ATTEMPTS',
  // CORS / rate limit / uploads / logging
  'ALLOWED_ORIGINS',
  'CORS_CREDENTIALS',
  'RATE_LIMIT_WINDOW_MS',
  'RATE_LIMIT_MAX_REQUESTS',
  'UPLOAD_DIR',
  'MAX_FILE_SIZE',
  'ALLOWED_FILE_TYPES',
  'ALLOWED_IMAGE_TYPES',
  'ALLOWED_DOCUMENT_TYPES',
  'MAX_IMAGES_PER_AD',
  'LOG_LEVEL',
  'LOG_FILE',
  // Payments
  'RAZORPAY_KEY_ID',
  'RAZORPAY_KEY_SECRET',
  'RAZORPAY_WEBHOOK_SECRET',
  // Firebase
  'FIREBASE_PROJECT_ID',
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'FIREBASE_MEASUREMENT_ID',
  'FIREBASE_SERVICE_ACCOUNT_PATH',
  'FIREBASE_VAPID_KEY',
  // SMS
  'SMS_BRAND',
  'SMS_PROVIDER',
  'SMS_API_KEY',
  'SMS_SENDER_ID',
  'SMS_BASE_URL',
  'SMS_FORMAT',
  'SMS_UNICODE',
  'SMS_USE_TEMPLATE_ID',
  'SMS_DLT_TEMPLATE_ID',
  'SMS_OTP_TEMPLATE_ID',
  'SMS_AD_APPROVED_TEMPLATE_ID',
  'SMS_AD_REJECTED_TEMPLATE_ID',
  'SMS_AD_REVIEW_TEMPLATE_ID',
  'SMS_AD_EXPIRED_TEMPLATE_ID',
  'SMS_AD_EXTENDED_TEMPLATE_ID',
  'SMS_AD_WILL_EXPIRE_TEMPLATE_ID',
  // Email
  'SMTP_HOST',
  'SMTP_PORT',
  'SMTP_USER',
  'SMTP_PASS',
  'FROM_EMAIL',
  'FROM_NAME',
  // Misc
  'TEST_OTP',
  'GOOGLE_MAPS_API_KEY',
];

/** Admin-only server secrets (Next route handlers; never NEXT_PUBLIC_). */
const ADMIN_EXTRA_KEYS = [...FRONTEND_EXTRA_KEYS, 'HEAP_DUMP_SECRET'];

function check(env) {
  const issues = [];
  if (!env.JWT_SECRET || env.JWT_SECRET.length < 32) {
    issues.push('JWT_SECRET missing or shorter than 32 chars');
  }
  if (!env.DATABASE_URL) issues.push('DATABASE_URL missing');
  if (!env.POSTGRES_USER || !env.POSTGRES_PASSWORD || !env.POSTGRES_DB) {
    issues.push('POSTGRES_USER/PASSWORD/DB incomplete');
  }
  if (env.POSTGRES_HOST && env.POSTGRES_HOST !== 'db') {
    issues.push(`POSTGRES_HOST='${env.POSTGRES_HOST}' (Docker expects 'db')`);
  }
  if (env.REDIS_HOST && env.REDIS_HOST !== 'redis') {
    issues.push(`REDIS_HOST='${env.REDIS_HOST}' (Docker expects 'redis')`);
  }
  if ((env.DATABASE_URL || '').includes('@postgres:')) {
    issues.push("DATABASE_URL host 'postgres' is wrong — use 'db'");
  }
  return issues;
}

function sync(production = false) {
  const root = parseEnv(path.join(ROOT, '.env'));
  const rootLocal = production ? {} : parseEnv(path.join(ROOT, '.env.local'));
  const docker = withDockerHosts(root);
  const local = production
    ? docker
    : withLocalHosts({ ...root, ...rootLocal });

  // --- api ---
  const apiLocal = { ...local };
  if (apiLocal.API_PORT) apiLocal.PORT = apiLocal.API_PORT;
  write('api/.env', HDR + dump(docker, API_KEYS));
  if (production) {
    remove('api/.env.local');
  } else {
    write('api/.env.local', HDR + dump(apiLocal, API_KEYS));
  }

  // --- admin (Next reads .env then .env.local) ---
  const adminProd = { ...docker };
  if (adminProd.ADMIN_PORT) adminProd.PORT = adminProd.ADMIN_PORT;
  const adminLocal = { ...local };
  if (adminLocal.ADMIN_PORT) adminLocal.PORT = adminLocal.ADMIN_PORT;
  write(
    'admin/.env',
    HDR + dump(adminProd, allKeys(adminProd, ['NEXT_PUBLIC_'], ADMIN_EXTRA_KEYS))
  );
  if (production) {
    remove('admin/.env.local');
  } else {
    write(
      'admin/.env.local',
      HDR +
        dump(adminLocal, allKeys(adminLocal, ['NEXT_PUBLIC_'], ADMIN_EXTRA_KEYS))
    );
  }

  // --- mobile (public + EXPO_PUBLIC only; no payment secrets) ---
  write(
    'mobile/.env',
    HDR +
      dump(docker, allKeys(docker, ['EXPO_PUBLIC_', 'NEXT_PUBLIC_']))
  );
  if (production) {
    remove('mobile/.env.local');
  } else {
    write(
      'mobile/.env.local',
      HDR +
        dump(local, allKeys(local, ['EXPO_PUBLIC_', 'NEXT_PUBLIC_']))
    );
  }

  // Remove legacy names if present
  const legacy = [
    'api/.env.development',
    'api/.env.production',
    'admin/.env.development',
    'admin/.env.production',
    'mobile/.env.development',
    'mobile/.env.production',
  ];
  for (const rel of legacy) {
    const full = path.join(ROOT, rel);
    if (fs.existsSync(full)) {
      fs.unlinkSync(full);
      console.log(`  removed legacy ${rel}`);
    }
  }
}

function main() {
  const args = process.argv.slice(2);
  if (!fs.existsSync(path.join(ROOT, '.env'))) {
    console.error('Missing root .env — copy from .env.example');
    process.exit(1);
  }

  const root = parseEnv(path.join(ROOT, '.env'));
  const issues = check(root);
  const production = args.includes('--production');

  if (args.includes('--check')) {
    if (issues.length) {
      console.log('Issues in root .env:');
      issues.forEach((i) => console.log(`  - ${i}`));
      process.exit(1);
    }
    console.log('OK: root .env looks Docker-ready');
    process.exit(0);
  }

  if (production) {
    console.log('Syncing app .env from root .env (production, no .env.local)');
  } else {
    console.log('Syncing app .env + .env.local from root .env (+ .env.local)');
  }
  if (issues.length) {
    console.log('Warnings:');
    issues.forEach((i) => console.log(`  - ${i}`));
  }
  sync(production);
  console.log('Done. Edit root .env / .env.local only, then re-run ./pinn env:sync');
}

main();
